services:
  Auth-api:
    build:
      context: .
      dockerfile: Auth.Api/Dockerfile
    image: auth-api:local
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      HttpsRedirection__Enabled: "false"

      # برای ساده‌سازی (بدون .env) اتصال API به SQL کانتینری به صورت پیش‌فرض فعال است:
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=AuthDb;User Id=sa;Password=oAuth_Sql123!;TrustServerCertificate=True"

    ports:
      - "5000:8080"
    depends_on:
      sqlserver:
        condition: service_healthy
      sqlserver-init-authDb:
        condition: service_completed_successfully

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
      # پسورد باید سیاست SQL Server را پاس کند (حروف بزرگ/کوچک + عدد + کاراکتر خاص)
      SA_PASSWORD: "oAuth_Sql123!"
    ports:
      - "1436:1433"
    volumes:
      - tebdata-sql-data:/var/opt/mssql
    healthcheck:
      test: ["CMD", "timeout", "5", "bash", "-c", "echo > /dev/tcp/localhost/1433"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # یک‌بار بعد از بالا آمدن SQL Server اجرا می‌شود و دیتابیس را می‌سازد (اگر وجود نداشت)
  sqlserver-init-authDb:
    image: mcr.microsoft.com/mssql-tools:latest
    depends_on:
      sqlserver:
        condition: service_healthy
    command:
      - /bin/bash
      - -lc
      - |
        set -e
        until /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P "oAuth_Sql123!" -Q "SELECT 1" >/dev/null 2>&1; do
          echo "Waiting for SQL Server..."
          sleep 2
        done
        /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P "oAuth_Sql123!" -Q "IF DB_ID(N'AuthDb') IS NULL BEGIN CREATE DATABASE [AuthDb]; END"
        echo "Database AuthDb is ready."
    restart: "no"

volumes:
  tebdata-sql-data:
